---
title: "Untitled"
author: "Julia Annika Ferdin"
date: "2025-05-04"
output: html_document
---

Test



```{r}
read.csv("Daten/Daten.csv")

dat <- read.csv("Daten/Daten.csv")
```

```{r}
#General first overview of data

# Dimension
dim(dat)
# Number of columns
ncol(dat)
# Number of rows
nrow(dat)

colnames(dat)
rownames(dat)
head(dat)
summary(dat)
```

```{r}
#Check for missing values
sum(is.na(dat$Protein_Name.Fraction1_Ctrl_Rep1.Fraction1_RNase_Rep1.Fraction1_Ctrl_Rep2.Fraction1_RNase_Rep2.Fraction1_Ctrl_Rep3.Fraction1_RNase_Rep3.Fraction2_Ctrl_Rep1.Fraction2_RNase_Rep1.Fraction2_Ctrl_Rep2.Fraction2_RNase_Rep2.Fraction2_Ctrl_Rep3.Fraction2_RNase_Rep3.Fraction3_Ctrl_Rep1.Fraction3_RNase_Rep1.Fraction3_Ctrl_Rep2.Fraction3_RNase_Rep2.Fraction3_Ctrl_Rep3.Fraction3_RNase_Rep3.Fraction4_Ctrl_Rep1.Fraction4_RNase_Rep1.Fraction4_Ctrl_Rep2.Fraction4_RNase_Rep2.Fraction4_Ctrl_Rep3.Fraction4_RNase_Rep3.Fraction5_Ctrl_Rep1.Fraction5_RNase_Rep1.Fraction5_Ctrl_Rep2.Fraction5_RNase_Rep2.Fraction5_Ctrl_Rep3.Fraction5_RNase_Rep3.Fraction6_Ctrl_Rep1.Fraction6_RNase_Rep1.Fraction6_Ctrl_Rep2.Fraction6_RNase_Rep2.Fraction6_Ctrl_Rep3.Fraction6_RNase_Rep3.Fraction7_Ctrl_Rep1.Fraction7_RNase_Rep1.Fraction7_Ctrl_Rep2.Fraction7_RNase_Rep2.Fraction7_Ctrl_Rep3.Fraction7_RNase_Rep3.Fraction8_Ctrl_Rep1.Fraction8_RNase_Rep1.Fraction8_Ctrl_Rep2.Fraction8_RNase_Rep2.Fraction8_Ctrl_Rep3.Fraction8_RNase_Rep3.Fraction9_Ctrl_Rep1.Fraction9_RNase_Rep1.Fraction9_Ctrl_Rep2.Fraction9_RNase_Rep2.Fraction9_Ctrl_Rep3.Fraction9_RNase_Rep3.Fraction10_Ctrl_Rep1.Fraction10_RNase_Rep1.Fraction10_Ctrl_Rep2.Fraction10_RNase_Rep2.Fraction10_Ctrl_Rep3.Fraction10_RNase_Rep3.Fraction11_Ctrl_Rep1.Fraction11_RNase_Rep1.Fraction11_Ctrl_Rep2.Fraction11_RNase_Rep2.Fraction11_Ctrl_Rep3.Fraction11_RNase_Rep3.Fraction12_Ctrl_Rep1.Fraction12_RNase_Rep1.Fraction12_Ctrl_Rep2.Fraction12_RNase_Rep2.Fraction12_Ctrl_Rep3.Fraction12_RNase_Rep3.Fraction13_Ctrl_Rep1.Fraction13_RNase_Rep1.Fraction13_Ctrl_Rep2.Fraction13_RNase_Rep2.Fraction13_Ctrl_Rep3.Fraction13_RNase_Rep3.Fraction14_Ctrl_Rep1.Fraction14_RNase_Rep1.Fraction14_Ctrl_Rep2.Fraction14_RNase_Rep2.Fraction14_Ctrl_Rep3.Fraction14_RNase_Rep3.Fraction15_Ctrl_Rep1.Fraction15_RNase_Rep1.Fraction15_Ctrl_Rep2.Fraction15_RNase_Rep2.Fraction15_Ctrl_Rep3.Fraction15_RNase_Rep3.Fraction16_Ctrl_Rep1.Fraction16_RNase_Rep1.Fraction16_Ctrl_Rep2.Fraction16_RNase_Rep2.Fraction16_Ctrl_Rep3.Fraction16_RNase_Rep3.Fraction17_Ctrl_Rep1.Fraction17_RNase_Rep1.Fraction17_Ctrl_Rep2.Fraction17_RNase_Rep2.Fraction17_Ctrl_Rep3.Fraction17_RNase_Rep3.Fraction18_Ctrl_Rep1.Fraction18_RNase_Rep1.Fraction18_Ctrl_Rep2.Fraction18_RNase_Rep2.Fraction18_Ctrl_Rep3.Fraction18_RNase_Rep3.Fraction19_Ctrl_Rep1.Fraction19_RNase_Rep1.Fraction19_Ctrl_Rep2.Fraction19_RNase_Rep2.Fraction19_Ctrl_Rep3.Fraction19_RNase_Rep3.Fraction20_Ctrl_Rep1.Fraction20_RNase_Rep1.Fraction20_Ctrl_Rep2.Fraction20_RNase_Rep2.Fraction20_Ctrl_Rep3.Fraction20_RNase_Rep3.Fraction21_Ctrl_Rep1.Fraction21_RNase_Rep1.Fraction21_Ctrl_Rep2.Fraction21_RNase_Rep2.Fraction21_Ctrl_Rep3.Fraction21_RNase_Rep3.Fraction22_Ctrl_Rep1.Fraction22_RNase_Rep1.Fraction22_Ctrl_Rep2.Fraction22_RNase_Rep2.Fraction22_Ctrl_Rep3.Fraction22_RNase_Rep3.Fraction23_Ctrl_Rep1.Fraction23_RNase_Rep1.Fraction23_Ctrl_Rep2.Fraction23_RNase_Rep2.Fraction23_Ctrl_Rep3.Fraction23_RNase_Rep3.Fraction24_Ctrl_Rep1.Fraction24_RNase_Rep1.Fraction24_Ctrl_Rep2.Fraction24_RNase_Rep2.Fraction24_Ctrl_Rep3.Fraction24_RNase_Rep3.Fraction25_Ctrl_Rep1.Fraction25_RNase_Rep1.Fraction25_Ctrl_Rep2.Fraction25_RNase_Rep2.Fraction25_Ctrl_Rep3.Fraction25_RNase_Rep3))
```
```{r}
# set the row names using the column
rownames(dat) = dat$Protein_Name.Fraction1_Ctrl_Rep1.Fraction1_RNase_Rep1.Fraction1_Ctrl_Rep2.Fraction1_RNase_Rep2.Fraction1_Ctrl_Rep3.Fraction1_RNase_Rep3.Fraction2_Ctrl_Rep1.Fraction2_RNase_Rep1.Fraction2_Ctrl_Rep2.Fraction2_RNase_Rep2.Fraction2_Ctrl_Rep3.Fraction2_RNase_Rep3.Fraction3_Ctrl_Rep1.Fraction3_RNase_Rep1.Fraction3_Ctrl_Rep2.Fraction3_RNase_Rep2.Fraction3_Ctrl_Rep3.Fraction3_RNase_Rep3.Fraction4_Ctrl_Rep1.Fraction4_RNase_Rep1.Fraction4_Ctrl_Rep2.Fraction4_RNase_Rep2.Fraction4_Ctrl_Rep3.Fraction4_RNase_Rep3.Fraction5_Ctrl_Rep1.Fraction5_RNase_Rep1.Fraction5_Ctrl_Rep2.Fraction5_RNase_Rep2.Fraction5_Ctrl_Rep3.Fraction5_RNase_Rep3.Fraction6_Ctrl_Rep1.Fraction6_RNase_Rep1.Fraction6_Ctrl_Rep2.Fraction6_RNase_Rep2.Fraction6_Ctrl_Rep3.Fraction6_RNase_Rep3.Fraction7_Ctrl_Rep1.Fraction7_RNase_Rep1.Fraction7_Ctrl_Rep2.Fraction7_RNase_Rep2.Fraction7_Ctrl_Rep3.Fraction7_RNase_Rep3.Fraction8_Ctrl_Rep1.Fraction8_RNase_Rep1.Fraction8_Ctrl_Rep2.Fraction8_RNase_Rep2.Fraction8_Ctrl_Rep3.Fraction8_RNase_Rep3.Fraction9_Ctrl_Rep1.Fraction9_RNase_Rep1.Fraction9_Ctrl_Rep2.Fraction9_RNase_Rep2.Fraction9_Ctrl_Rep3.Fraction9_RNase_Rep3.Fraction10_Ctrl_Rep1.Fraction10_RNase_Rep1.Fraction10_Ctrl_Rep2.Fraction10_RNase_Rep2.Fraction10_Ctrl_Rep3.Fraction10_RNase_Rep3.Fraction11_Ctrl_Rep1.Fraction11_RNase_Rep1.Fraction11_Ctrl_Rep2.Fraction11_RNase_Rep2.Fraction11_Ctrl_Rep3.Fraction11_RNase_Rep3.Fraction12_Ctrl_Rep1.Fraction12_RNase_Rep1.Fraction12_Ctrl_Rep2.Fraction12_RNase_Rep2.Fraction12_Ctrl_Rep3.Fraction12_RNase_Rep3.Fraction13_Ctrl_Rep1.Fraction13_RNase_Rep1.Fraction13_Ctrl_Rep2.Fraction13_RNase_Rep2.Fraction13_Ctrl_Rep3.Fraction13_RNase_Rep3.Fraction14_Ctrl_Rep1.Fraction14_RNase_Rep1.Fraction14_Ctrl_Rep2.Fraction14_RNase_Rep2.Fraction14_Ctrl_Rep3.Fraction14_RNase_Rep3.Fraction15_Ctrl_Rep1.Fraction15_RNase_Rep1.Fraction15_Ctrl_Rep2.Fraction15_RNase_Rep2.Fraction15_Ctrl_Rep3.Fraction15_RNase_Rep3.Fraction16_Ctrl_Rep1.Fraction16_RNase_Rep1.Fraction16_Ctrl_Rep2.Fraction16_RNase_Rep2.Fraction16_Ctrl_Rep3.Fraction16_RNase_Rep3.Fraction17_Ctrl_Rep1.Fraction17_RNase_Rep1.Fraction17_Ctrl_Rep2.Fraction17_RNase_Rep2.Fraction17_Ctrl_Rep3.Fraction17_RNase_Rep3.Fraction18_Ctrl_Rep1.Fraction18_RNase_Rep1.Fraction18_Ctrl_Rep2.Fraction18_RNase_Rep2.Fraction18_Ctrl_Rep3.Fraction18_RNase_Rep3.Fraction19_Ctrl_Rep1.Fraction19_RNase_Rep1.Fraction19_Ctrl_Rep2.Fraction19_RNase_Rep2.Fraction19_Ctrl_Rep3.Fraction19_RNase_Rep3.Fraction20_Ctrl_Rep1.Fraction20_RNase_Rep1.Fraction20_Ctrl_Rep2.Fraction20_RNase_Rep2.Fraction20_Ctrl_Rep3.Fraction20_RNase_Rep3.Fraction21_Ctrl_Rep1.Fraction21_RNase_Rep1.Fraction21_Ctrl_Rep2.Fraction21_RNase_Rep2.Fraction21_Ctrl_Rep3.Fraction21_RNase_Rep3.Fraction22_Ctrl_Rep1.Fraction22_RNase_Rep1.Fraction22_Ctrl_Rep2.Fraction22_RNase_Rep2.Fraction22_Ctrl_Rep3.Fraction22_RNase_Rep3.Fraction23_Ctrl_Rep1.Fraction23_RNase_Rep1.Fraction23_Ctrl_Rep2.Fraction23_RNase_Rep2.Fraction23_Ctrl_Rep3.Fraction23_RNase_Rep3.Fraction24_Ctrl_Rep1.Fraction24_RNase_Rep1.Fraction24_Ctrl_Rep2.Fraction24_RNase_Rep2.Fraction24_Ctrl_Rep3.Fraction24_RNase_Rep3.Fraction25_Ctrl_Rep1.Fraction25_RNase_Rep1.Fraction25_Ctrl_Rep2.Fraction25_RNase_Rep2.Fraction25_Ctrl_Rep3.Fraction25_RNase_Rep3
```

```{r}
#Visualizing data
hist(dat$Protein_Name.Fraction1_Ctrl_Rep1.Fraction1_RNase_Rep1.Fraction1_Ctrl_Rep2.Fraction1_RNase_Rep2.Fraction1_Ctrl_Rep3.Fraction1_RNase_Rep3.Fraction2_Ctrl_Rep1.Fraction2_RNase_Rep1.Fraction2_Ctrl_Rep2.Fraction2_RNase_Rep2.Fraction2_Ctrl_Rep3.Fraction2_RNase_Rep3.Fraction3_Ctrl_Rep1.Fraction3_RNase_Rep1.Fraction3_Ctrl_Rep2.Fraction3_RNase_Rep2.Fraction3_Ctrl_Rep3.Fraction3_RNase_Rep3.Fraction4_Ctrl_Rep1.Fraction4_RNase_Rep1.Fraction4_Ctrl_Rep2.Fraction4_RNase_Rep2.Fraction4_Ctrl_Rep3.Fraction4_RNase_Rep3.Fraction5_Ctrl_Rep1.Fraction5_RNase_Rep1.Fraction5_Ctrl_Rep2.Fraction5_RNase_Rep2.Fraction5_Ctrl_Rep3.Fraction5_RNase_Rep3.Fraction6_Ctrl_Rep1.Fraction6_RNase_Rep1.Fraction6_Ctrl_Rep2.Fraction6_RNase_Rep2.Fraction6_Ctrl_Rep3.Fraction6_RNase_Rep3.Fraction7_Ctrl_Rep1.Fraction7_RNase_Rep1.Fraction7_Ctrl_Rep2.Fraction7_RNase_Rep2.Fraction7_Ctrl_Rep3.Fraction7_RNase_Rep3.Fraction8_Ctrl_Rep1.Fraction8_RNase_Rep1.Fraction8_Ctrl_Rep2.Fraction8_RNase_Rep2.Fraction8_Ctrl_Rep3.Fraction8_RNase_Rep3.Fraction9_Ctrl_Rep1.Fraction9_RNase_Rep1.Fraction9_Ctrl_Rep2.Fraction9_RNase_Rep2.Fraction9_Ctrl_Rep3.Fraction9_RNase_Rep3.Fraction10_Ctrl_Rep1.Fraction10_RNase_Rep1.Fraction10_Ctrl_Rep2.Fraction10_RNase_Rep2.Fraction10_Ctrl_Rep3.Fraction10_RNase_Rep3.Fraction11_Ctrl_Rep1.Fraction11_RNase_Rep1.Fraction11_Ctrl_Rep2.Fraction11_RNase_Rep2.Fraction11_Ctrl_Rep3.Fraction11_RNase_Rep3.Fraction12_Ctrl_Rep1.Fraction12_RNase_Rep1.Fraction12_Ctrl_Rep2.Fraction12_RNase_Rep2.Fraction12_Ctrl_Rep3.Fraction12_RNase_Rep3.Fraction13_Ctrl_Rep1.Fraction13_RNase_Rep1.Fraction13_Ctrl_Rep2.Fraction13_RNase_Rep2.Fraction13_Ctrl_Rep3.Fraction13_RNase_Rep3.Fraction14_Ctrl_Rep1.Fraction14_RNase_Rep1.Fraction14_Ctrl_Rep2.Fraction14_RNase_Rep2.Fraction14_Ctrl_Rep3.Fraction14_RNase_Rep3.Fraction15_Ctrl_Rep1.Fraction15_RNase_Rep1.Fraction15_Ctrl_Rep2.Fraction15_RNase_Rep2.Fraction15_Ctrl_Rep3.Fraction15_RNase_Rep3.Fraction16_Ctrl_Rep1.Fraction16_RNase_Rep1.Fraction16_Ctrl_Rep2.Fraction16_RNase_Rep2.Fraction16_Ctrl_Rep3.Fraction16_RNase_Rep3.Fraction17_Ctrl_Rep1.Fraction17_RNase_Rep1.Fraction17_Ctrl_Rep2.Fraction17_RNase_Rep2.Fraction17_Ctrl_Rep3.Fraction17_RNase_Rep3.Fraction18_Ctrl_Rep1.Fraction18_RNase_Rep1.Fraction18_Ctrl_Rep2.Fraction18_RNase_Rep2.Fraction18_Ctrl_Rep3.Fraction18_RNase_Rep3.Fraction19_Ctrl_Rep1.Fraction19_RNase_Rep1.Fraction19_Ctrl_Rep2.Fraction19_RNase_Rep2.Fraction19_Ctrl_Rep3.Fraction19_RNase_Rep3.Fraction20_Ctrl_Rep1.Fraction20_RNase_Rep1.Fraction20_Ctrl_Rep2.Fraction20_RNase_Rep2.Fraction20_Ctrl_Rep3.Fraction20_RNase_Rep3.Fraction21_Ctrl_Rep1.Fraction21_RNase_Rep1.Fraction21_Ctrl_Rep2.Fraction21_RNase_Rep2.Fraction21_Ctrl_Rep3.Fraction21_RNase_Rep3.Fraction22_Ctrl_Rep1.Fraction22_RNase_Rep1.Fraction22_Ctrl_Rep2.Fraction22_RNase_Rep2.Fraction22_Ctrl_Rep3.Fraction22_RNase_Rep3.Fraction23_Ctrl_Rep1.Fraction23_RNase_Rep1.Fraction23_Ctrl_Rep2.Fraction23_RNase_Rep2.Fraction23_Ctrl_Rep3.Fraction23_RNase_Rep3.Fraction24_Ctrl_Rep1.Fraction24_RNase_Rep1.Fraction24_Ctrl_Rep2.Fraction24_RNase_Rep2.Fraction24_Ctrl_Rep3.Fraction24_RNase_Rep3.Fraction25_Ctrl_Rep1.Fraction25_RNase_Rep1.Fraction25_Ctrl_Rep2.Fraction25_RNase_Rep2.Fraction25_Ctrl_Rep3.Fraction25_RNase_Rep3, xlab ="X", main ="Y")

d <- density(dat$Protein_Name.Fraction1_Ctrl_Rep1.Fraction1_RNase_Rep1.Fraction1_Ctrl_Rep2.Fraction1_RNase_Rep2.Fraction1_Ctrl_Rep3.Fraction1_RNase_Rep3.Fraction2_Ctrl_Rep1.Fraction2_RNase_Rep1.Fraction2_Ctrl_Rep2.Fraction2_RNase_Rep2.Fraction2_Ctrl_Rep3.Fraction2_RNase_Rep3.Fraction3_Ctrl_Rep1.Fraction3_RNase_Rep1.Fraction3_Ctrl_Rep2.Fraction3_RNase_Rep2.Fraction3_Ctrl_Rep3.Fraction3_RNase_Rep3.Fraction4_Ctrl_Rep1.Fraction4_RNase_Rep1.Fraction4_Ctrl_Rep2.Fraction4_RNase_Rep2.Fraction4_Ctrl_Rep3.Fraction4_RNase_Rep3.Fraction5_Ctrl_Rep1.Fraction5_RNase_Rep1.Fraction5_Ctrl_Rep2.Fraction5_RNase_Rep2.Fraction5_Ctrl_Rep3.Fraction5_RNase_Rep3.Fraction6_Ctrl_Rep1.Fraction6_RNase_Rep1.Fraction6_Ctrl_Rep2.Fraction6_RNase_Rep2.Fraction6_Ctrl_Rep3.Fraction6_RNase_Rep3.Fraction7_Ctrl_Rep1.Fraction7_RNase_Rep1.Fraction7_Ctrl_Rep2.Fraction7_RNase_Rep2.Fraction7_Ctrl_Rep3.Fraction7_RNase_Rep3.Fraction8_Ctrl_Rep1.Fraction8_RNase_Rep1.Fraction8_Ctrl_Rep2.Fraction8_RNase_Rep2.Fraction8_Ctrl_Rep3.Fraction8_RNase_Rep3.Fraction9_Ctrl_Rep1.Fraction9_RNase_Rep1.Fraction9_Ctrl_Rep2.Fraction9_RNase_Rep2.Fraction9_Ctrl_Rep3.Fraction9_RNase_Rep3.Fraction10_Ctrl_Rep1.Fraction10_RNase_Rep1.Fraction10_Ctrl_Rep2.Fraction10_RNase_Rep2.Fraction10_Ctrl_Rep3.Fraction10_RNase_Rep3.Fraction11_Ctrl_Rep1.Fraction11_RNase_Rep1.Fraction11_Ctrl_Rep2.Fraction11_RNase_Rep2.Fraction11_Ctrl_Rep3.Fraction11_RNase_Rep3.Fraction12_Ctrl_Rep1.Fraction12_RNase_Rep1.Fraction12_Ctrl_Rep2.Fraction12_RNase_Rep2.Fraction12_Ctrl_Rep3.Fraction12_RNase_Rep3.Fraction13_Ctrl_Rep1.Fraction13_RNase_Rep1.Fraction13_Ctrl_Rep2.Fraction13_RNase_Rep2.Fraction13_Ctrl_Rep3.Fraction13_RNase_Rep3.Fraction14_Ctrl_Rep1.Fraction14_RNase_Rep1.Fraction14_Ctrl_Rep2.Fraction14_RNase_Rep2.Fraction14_Ctrl_Rep3.Fraction14_RNase_Rep3.Fraction15_Ctrl_Rep1.Fraction15_RNase_Rep1.Fraction15_Ctrl_Rep2.Fraction15_RNase_Rep2.Fraction15_Ctrl_Rep3.Fraction15_RNase_Rep3.Fraction16_Ctrl_Rep1.Fraction16_RNase_Rep1.Fraction16_Ctrl_Rep2.Fraction16_RNase_Rep2.Fraction16_Ctrl_Rep3.Fraction16_RNase_Rep3.Fraction17_Ctrl_Rep1.Fraction17_RNase_Rep1.Fraction17_Ctrl_Rep2.Fraction17_RNase_Rep2.Fraction17_Ctrl_Rep3.Fraction17_RNase_Rep3.Fraction18_Ctrl_Rep1.Fraction18_RNase_Rep1.Fraction18_Ctrl_Rep2.Fraction18_RNase_Rep2.Fraction18_Ctrl_Rep3.Fraction18_RNase_Rep3.Fraction19_Ctrl_Rep1.Fraction19_RNase_Rep1.Fraction19_Ctrl_Rep2.Fraction19_RNase_Rep2.Fraction19_Ctrl_Rep3.Fraction19_RNase_Rep3.Fraction20_Ctrl_Rep1.Fraction20_RNase_Rep1.Fraction20_Ctrl_Rep2.Fraction20_RNase_Rep2.Fraction20_Ctrl_Rep3.Fraction20_RNase_Rep3.Fraction21_Ctrl_Rep1.Fraction21_RNase_Rep1.Fraction21_Ctrl_Rep2.Fraction21_RNase_Rep2.Fraction21_Ctrl_Rep3.Fraction21_RNase_Rep3.Fraction22_Ctrl_Rep1.Fraction22_RNase_Rep1.Fraction22_Ctrl_Rep2.Fraction22_RNase_Rep2.Fraction22_Ctrl_Rep3.Fraction22_RNase_Rep3.Fraction23_Ctrl_Rep1.Fraction23_RNase_Rep1.Fraction23_Ctrl_Rep2.Fraction23_RNase_Rep2.Fraction23_Ctrl_Rep3.Fraction23_RNase_Rep3.Fraction24_Ctrl_Rep1.Fraction24_RNase_Rep1.Fraction24_Ctrl_Rep2.Fraction24_RNase_Rep2.Fraction24_Ctrl_Rep3.Fraction24_RNase_Rep3.Fraction25_Ctrl_Rep1.Fraction25_RNase_Rep1.Fraction25_Ctrl_Rep2.Fraction25_RNase_Rep2.Fraction25_Ctrl_Rep3.Fraction25_RNase_Rep3)
plot(d, xlab ="X", main ="Y")

boxplot(dat$Protein_Name.Fraction1_Ctrl_Rep1.Fraction1_RNase_Rep1.Fraction1_Ctrl_Rep2.Fraction1_RNase_Rep2.Fraction1_Ctrl_Rep3.Fraction1_RNase_Rep3.Fraction2_Ctrl_Rep1.Fraction2_RNase_Rep1.Fraction2_Ctrl_Rep2.Fraction2_RNase_Rep2.Fraction2_Ctrl_Rep3.Fraction2_RNase_Rep3.Fraction3_Ctrl_Rep1.Fraction3_RNase_Rep1.Fraction3_Ctrl_Rep2.Fraction3_RNase_Rep2.Fraction3_Ctrl_Rep3.Fraction3_RNase_Rep3.Fraction4_Ctrl_Rep1.Fraction4_RNase_Rep1.Fraction4_Ctrl_Rep2.Fraction4_RNase_Rep2.Fraction4_Ctrl_Rep3.Fraction4_RNase_Rep3.Fraction5_Ctrl_Rep1.Fraction5_RNase_Rep1.Fraction5_Ctrl_Rep2.Fraction5_RNase_Rep2.Fraction5_Ctrl_Rep3.Fraction5_RNase_Rep3.Fraction6_Ctrl_Rep1.Fraction6_RNase_Rep1.Fraction6_Ctrl_Rep2.Fraction6_RNase_Rep2.Fraction6_Ctrl_Rep3.Fraction6_RNase_Rep3.Fraction7_Ctrl_Rep1.Fraction7_RNase_Rep1.Fraction7_Ctrl_Rep2.Fraction7_RNase_Rep2.Fraction7_Ctrl_Rep3.Fraction7_RNase_Rep3.Fraction8_Ctrl_Rep1.Fraction8_RNase_Rep1.Fraction8_Ctrl_Rep2.Fraction8_RNase_Rep2.Fraction8_Ctrl_Rep3.Fraction8_RNase_Rep3.Fraction9_Ctrl_Rep1.Fraction9_RNase_Rep1.Fraction9_Ctrl_Rep2.Fraction9_RNase_Rep2.Fraction9_Ctrl_Rep3.Fraction9_RNase_Rep3.Fraction10_Ctrl_Rep1.Fraction10_RNase_Rep1.Fraction10_Ctrl_Rep2.Fraction10_RNase_Rep2.Fraction10_Ctrl_Rep3.Fraction10_RNase_Rep3.Fraction11_Ctrl_Rep1.Fraction11_RNase_Rep1.Fraction11_Ctrl_Rep2.Fraction11_RNase_Rep2.Fraction11_Ctrl_Rep3.Fraction11_RNase_Rep3.Fraction12_Ctrl_Rep1.Fraction12_RNase_Rep1.Fraction12_Ctrl_Rep2.Fraction12_RNase_Rep2.Fraction12_Ctrl_Rep3.Fraction12_RNase_Rep3.Fraction13_Ctrl_Rep1.Fraction13_RNase_Rep1.Fraction13_Ctrl_Rep2.Fraction13_RNase_Rep2.Fraction13_Ctrl_Rep3.Fraction13_RNase_Rep3.Fraction14_Ctrl_Rep1.Fraction14_RNase_Rep1.Fraction14_Ctrl_Rep2.Fraction14_RNase_Rep2.Fraction14_Ctrl_Rep3.Fraction14_RNase_Rep3.Fraction15_Ctrl_Rep1.Fraction15_RNase_Rep1.Fraction15_Ctrl_Rep2.Fraction15_RNase_Rep2.Fraction15_Ctrl_Rep3.Fraction15_RNase_Rep3.Fraction16_Ctrl_Rep1.Fraction16_RNase_Rep1.Fraction16_Ctrl_Rep2.Fraction16_RNase_Rep2.Fraction16_Ctrl_Rep3.Fraction16_RNase_Rep3.Fraction17_Ctrl_Rep1.Fraction17_RNase_Rep1.Fraction17_Ctrl_Rep2.Fraction17_RNase_Rep2.Fraction17_Ctrl_Rep3.Fraction17_RNase_Rep3.Fraction18_Ctrl_Rep1.Fraction18_RNase_Rep1.Fraction18_Ctrl_Rep2.Fraction18_RNase_Rep2.Fraction18_Ctrl_Rep3.Fraction18_RNase_Rep3.Fraction19_Ctrl_Rep1.Fraction19_RNase_Rep1.Fraction19_Ctrl_Rep2.Fraction19_RNase_Rep2.Fraction19_Ctrl_Rep3.Fraction19_RNase_Rep3.Fraction20_Ctrl_Rep1.Fraction20_RNase_Rep1.Fraction20_Ctrl_Rep2.Fraction20_RNase_Rep2.Fraction20_Ctrl_Rep3.Fraction20_RNase_Rep3.Fraction21_Ctrl_Rep1.Fraction21_RNase_Rep1.Fraction21_Ctrl_Rep2.Fraction21_RNase_Rep2.Fraction21_Ctrl_Rep3.Fraction21_RNase_Rep3.Fraction22_Ctrl_Rep1.Fraction22_RNase_Rep1.Fraction22_Ctrl_Rep2.Fraction22_RNase_Rep2.Fraction22_Ctrl_Rep3.Fraction22_RNase_Rep3.Fraction23_Ctrl_Rep1.Fraction23_RNase_Rep1.Fraction23_Ctrl_Rep2.Fraction23_RNase_Rep2.Fraction23_Ctrl_Rep3.Fraction23_RNase_Rep3.Fraction24_Ctrl_Rep1.Fraction24_RNase_Rep1.Fraction24_Ctrl_Rep2.Fraction24_RNase_Rep2.Fraction24_Ctrl_Rep3.Fraction24_RNase_Rep3.Fraction25_Ctrl_Rep1.Fraction25_RNase_Rep1.Fraction25_Ctrl_Rep2.Fraction25_RNase_Rep2.Fraction25_Ctrl_Rep3.Fraction25_RNase_Rep3, xlab ="X", horizontal = TRUE)
```

